---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
        - containerPort: 7878
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: radarr
        - name: storage
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-configs
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.69.1.156
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
    name: http
  selector:
    app: radarr
