apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.69.1.160
  selector:
    app: overseerr
  ports:
  - name: http
    port: 5055
    targetPort: 5055
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        ports:
        - containerPort: 5055
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: overseerr
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-configs
