apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.69.1.150
  selector:
    app: plex
  ports:
  - name: plex
    port: 32400
    targetPort: 32400
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      # Fix NFS permissions - prevents "Operation not permitted" errors
      # Ensures Preferences.xml (containing PlexOnlineToken) persists across restarts
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
          name: plex
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: VERSION
          value: "docker"
        # NOTE: PLEX_CLAIM removed - no longer needed!
        # Server maintains authentication via PlexOnlineToken in Preferences.xml
        # Token persists across restarts thanks to securityContext fixes above
        # If you ever need to claim a FRESH server, use: kubectl set env deployment/plex PLEX_CLAIM=claim-XXX -n media
        # Hardware Transcoding (AMD GPU)
        - name: PLEX_PREFERENCE_1
          value: "TranscoderTempDirectory=/transcode"
        - name: PLEX_PREFERENCE_2
          value: "HardwareAcceleratedCodecs=1"
        # Resource management
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: plex
        - name: storage
          mountPath: /data
        # Fast local storage for transcoding (NOT NFS)
        - name: transcode
          mountPath: /transcode
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-configs
      - name: storage
        persistentVolumeClaim:
          claimName: media-storage
      # emptyDir uses local node storage (much faster than NFS)
      - name: transcode
        emptyDir:
          sizeLimit: 20Gi
