apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.69.1.158
  selector:
    app: qbittorrent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: torrent-tcp
    port: 6881
    targetPort: 6881
    protocol: TCP
  - name: torrent-udp
    port: 6881
    targetPort: 6881
    protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 6881
          name: torrent-tcp
          protocol: TCP
        - containerPort: 6881
          name: torrent-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBUI_PORT
          value: "8080"
        # Resource management
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: qbittorrent
        - name: downloads
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-configs
      - name: downloads
        persistentVolumeClaim:
          claimName: media-storage
